### ISSUE TITLE
Start in background on boot, not foreground

### ISSUE THREAD

**Issue by dreeves** [beeminder/beedroid-issues#102]
Complaint: starting on boot is good but not literally opening the app in your face.

Seems like this started happening in 3.0.2.

**Comment by dreeves** [comment]
New 3-star review just now: "Confused by the new "start at boot" update. What is the purpose? Seems rather clumsy and irritating to me."

I guess I should also understand what the answer is. Was it intentional? Easy to undo?

**Comment by adamwolf** [comment]
Without start-at-boot, we can't schedule any notifications until users open the application.  We get users complaining that they didn't get notifications.

I added start at boot to just start the application, not any particular screen, but about 10% of phones ended up crashing the app and showing a message that Beeminder had crashed.  Those phones need to start an activity (think screen), not an application.  I picked the most obvious one we had, to me, but it looks like it's confusing to folks.

I can create a new activity that just opens a toast which'll be up for a few seconds then go away.  I have four or five applications on my phone that do that. Open to other thoughts too.

**Comment by adamwolf** [comment]
(I thought I had responded to this but it looks like it's in Gmail's "outbox".  Since when did Gmail have an outbox?!)

**Comment by dreeves** [comment]
toast sounds perfect to me!

**Comment by adamwolf** [comment]
Working on this today for the upcoming 3.1.0 release.

**Comment by adamwolf** [comment]
Fixed in 3.1.0
