### ISSUE TITLE
Do not display graphs in goal overview

### ISSUE THREAD

**Issue by matkoniecz** [beeminder/beedroid-issues#121]
For me main result of displaying graph images in goal list is partially hiding names of some of my goals.

I assume that maybe graphs are useful for some people. But in case of open sourcing beedroid removing them would be the first thing to change in my fork.

**Comment by adamwolf** [comment]
Hi! Can you upload a screenshot of the goal list page so I can see what you're talking about?

**Comment by matkoniecz** [comment]
Note two last goals with name cut off by useless (for me) graphs.

There are also more flustrating blocked names, making dinnertime unclear what the goal is about (but mixed with more private goals)

![Screenshot_20200102-192108](https://user-images.githubusercontent.com/899988/71684201-1ee62e00-2d95-11ea-8083-1c3e52afc77d.png)

**Comment by adamwolf** [comment]
Ah, I see.

Have you tried using the list widget?  That might be a good way to get a
list of your goals without graph images.

**Comment by matkoniecz** [comment]
Yes! It is really great, I have it on my primary screen. I now reconfigured it to make it even larger, I will try using it as a primary interface for now.

In case of also this being not enough I will try making a new secondary screen, just with a giant beeminder list widget.

So I will close this issue and reopen in case that it turns to not work properly.

**Comment by matkoniecz** [comment]
Thanks for the suggestion! It actually matches very closely what I want (not exactly, but very close).
