### ISSUE TITLE
Ruthlessly purge settings: "check for graph updates" frequency

### ISSUE THREAD

**Issue by dreeves** [beeminder/beedroid-issues#136]
Beedroid's "check for graph updates" setting (options = {only morning, q4h, q2h, q1h, q30m, q15m}) is begging to be killed. http://doc.bmndr.com/choices

(btw "q4h", if i'm using it right, is medical lingo for "every 4 hours")

Adam points out that this is intertwined with some bigger issues with Android's sync framework. And the philosophical question of whether to support Android devices without Google Play Services?

But could we start with just yanking it from the UI and figure out the rest behind the scenes without that setting complicating things further?

**Comment by adamwolf** [comment]
If you don't have Google Play Services, you don't get push notifications, which means this is the only way you schedule syncs.

If we were going to remove the setting without redoing the sync framework thing, I would think we would want two different hardcoded settings, one for phones with Google Play Services, where we sync... hourly? and one for phones without, where something much more lax would be fine, like 4 hours.

I have no idea how many users we have who don't have Google Play Services.  Possibly none?  I'm not sure.

**Comment by adamwolf** [comment]
I have been making progress on #77, and as part of that, I removed this setting. It is not yet released.
