### ISSUE TITLE
User reports "Tasker integration seems to break if goal is changed from manual to API"

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#140]
Check on this.

https://forum.beeminder.com/t/tasker-integration-seems-to-break-if-goal-is-changed-from-manual-to-api/6971/1

**Comment by adamwolf** [comment]
This is real.

This looks like it has to do with the API authorization dialog. It excludes autodata goals, of which IFTTT, Zapier, and API are all included.

**Comment by StanczakDominik** [comment]
I wasn't hallucinating! Woo!

**Comment by adamwolf** [comment]
I was actually already changing an autodata thing, so I was already in it.  I took a quick look, and I found a bug that would do exactly what you described, even the "it doesn't immediately break..." part of it. My (unverified) guess is that it will break in the released version after you open the Tasker Integration screen, after you change the goal to API.

I have adjusted the check, and it seems to be working.  It'll be in the next release of the current beta.

I'll let you know here when that is, in case you're interested in testing it!

**Comment by StanczakDominik** [comment]
Sure, I love living on the edge of software dev ;) awesome that you've managed to find it!

**Comment by adamwolf** [comment]
This has been released.

**Comment by dreeves** [comment]
http://beeminder.com/changelog#3580
