### ISSUE TITLE
De-lane-ify the tally screen

### ISSUE THREAD

**Issue by dreeves** [beeminder/beedroid-issues#143]
Grep for 
* "Critical edge"
* "Centerline"
* "Good edge"

To Pareto-dominate that I guess we want the orange, blue, and green numbers from the dueby table.

![image](https://user-images.githubusercontent.com/9928/88712115-0f7e5780-d0ce-11ea-8d4c-4812061d50c3.png)

**Comment by adamwolf** [comment]
Should they be labeled "Critical edge", "Centerline", and "Good edge"?  What do those mean? (I mean this for real, like, I am not clear what any of those except critical edge means)

Critical edge means "the amount we need you to do today, not counting any that you've done on this screen but not yet submitted", right?

**Comment by dreeves** [comment]
All of those words should die, as should the checkmarks. What you want to know at the bottom of this screen is your delta if it's a beemergency, otherwise your daily rate and how many safe days you have. It's basically safesum. In fact, can we say we just stick safesum there?

**Comment by adamwolf** [comment]
We can put safesum there. Do we need a header? Do we need to somehow imply that it's not live? 

"+10 pushups due today" and then you do 20 pushups and it still says "+10 pushups due today"?

**Comment by dreeves** [comment]
Status quo ante wasn't live. User-me was never confused by that. Let's say not live, no header. Stick in safesum at the bottom and that's it.

**Comment by adamwolf** [comment]
This has been released.
