### ISSUE TITLE
Widgets broken on upgrade from 3.3 beta 2 to beta 3

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#148]
A user had their widgets broken when they upgraded.  They recreated all their widgets because they were stuck, and that worked.

**Comment by adamwolf** [comment]
This was due to the database migration code being incomplete.  I was able to reproduce this reliably, added a fix, and now cannot.

**Comment by jshholland** [comment]
I just upgraded to 3.3 (final, via the Play Store), and my "Bmndr summary" widget has reliably broken - it just shows "No goals!", even though they show up fine in the main app. I'm using the Nova Launcher on a Pixel 5.

**Comment by adamwolf** [comment]
What happens if you remove it and readd it?

**Comment by jshholland** [comment]
That doesn't help (which is what I meant by "reliably" but I guess that wasn't very clear).

**Comment by adamwolf** [comment]
Does the summary widget have a little refresh icon?  Can you tap that? Does that help?  If not, can you log out of the app, and log back in?  If none of that helps, can you reboot it?

Sorry for the hassle, thanks for being so fast to help troubleshoot this!

**Comment by jshholland** [comment]
Logging out and in again fixed it. I tried rebooting before and that didn't help, and neither did the little refresh icon.
