### ISSUE TITLE
Stop showing user name when I am searching for goal

### ISSUE THREAD

**Issue by matkoniecz** [beeminder/beedroid-issues#152]
It is quite irritating to be unable to distinguish goal, just because user name is displayed.

I have some memory issues but I do not need to be reminded how I am named.

![Screenshot_20200927-105305](https://user-images.githubusercontent.com/899988/94360729-fedb6500-00af-11eb-9d73-7cae9ab97c7f.png)

**Comment by matkoniecz** [comment]
At least in my case there are sometimes cases where search becomes useless, especially when combined with #72

This specific search is a bit naive, but I have for example goals with names such as ping_agata ping_agata_kowalska - searching for the first is extremely irritating

**Comment by adamwolf** [comment]
Beedroid allows multiple users to be logged into the same app, at the same time.

Usernames as goal prefixes are basically required when multiple users are logged in.

In the last few releases, we have been removing usernames as goal prefixes when there is only one user logged in.

The way we are searching for goals in Beedroid and doing this incremental search needs to be basically redone to match newer Android paradigms, so we get things like goals in the OS-wide search, for instance.

I'm not sure this will get done before it gets completely redone, but it's possible!

Thanks for the bug report.

**Comment by matkoniecz** [comment]
> In the last few releases, we have been removing usernames as goal prefixes when there is only one user logged in.

In this case only one user is logged in and I am running latest released version.

**Comment by StanczakDominik** [comment]
I'm running build 12643 (beta) and I also see my username, while I'm the only user logged in.

**Comment by adamwolf** [comment]
I'm sorry I wasn't clear.  The username/goalname is scattered throughout the app.  I haven't removed it from search yet, as search needs a larger overhaul.

**Comment by adamwolf** [comment]
Requested today by a different user.

**Comment by adamwolf** [comment]
This will be fixed in the next release.
