### ISSUE TITLE
Many transient popup notifications on sync on upgrade to 4.0.0

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#182]

**Comment by adamwolf** [comment]
Fixed in 4.0.1

**Comment by adamwolf** [comment]
UVI: Upgrading to 4.0.0 (and potentially other things) could cause a bunch of transient notifications on sync, but we fixed it in 4.0.1.

**Comment by dreeves** [comment]
http://beeminder.com/changelog#3672
