### ISSUE TITLE
It isn't obvious that lists go off the screen

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#185]
The impetus for this was the goal list widget. If you're in the middle of a big list, there's no indication that there's more at the top, which can make you think everything is hunky dory.

We brainstormed, and one idea was a line at the top and the bottom, and another was to fade non-end items if they're at the top or bottom.

This also affects the data list view.

**Comment by adamwolf** [comment]
For the fade, let's see what `android:requiresFadingEdge="vertical"` looks like.

**Comment by dreeves** [comment]
Nice work, y'all. User-datapoints so far are that this bit user-Nicky, and user-Danny finds the status quo fine.

If dev time were required here it might be worth getting more opinions but it sounds like adding that line could be the best of all worlds!

**Comment by adamwolf** [comment]
This has been released in Beedroid 5.
