### ISSUE TITLE
Investigate data submission right before closing the screen

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#188]
A user reports:

"On some occasions, if I don't keep the widget open until it submits the data and rebuilds the graph, it won't submit and then I derail"

This has been a problem since before the sync framework change.

**Comment by adamwolf** [comment]
Hold up, the user hasn't yet upgraded and is still on 2.7.0.

**Comment by adamwolf** [comment]
This has been solved as of the sync framework change.

**Comment by dreeves** [comment]
Sounds like this was fixed in http://beeminder.com/changelog#3580
