### ISSUE TITLE
Tiny copy change: "if you forgot it or never made one"

### ISSUE THREAD

**Issue by dreeves** [beeminder/beedroid-issues#191]
OLD: "reset your password [link] if you forgot it or never got one"
NEW: "reset your password [link] if you forgot it or never made one"

Related to the problem that Beedroid doesn't currently support Google sign-in so people think there's no way to log in to Beedroid if they only log in to Beeminder via Google oauth.

The above copy change makes it slightly clearer that they can create a password in Beeminder with which to log in to Beedroid.

**Comment by adamwolf** [comment]
This has been released in Beedroid 5.
