### ISSUE TITLE
Account for DST offsets when figuring out current timezone shortname

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#198]
> When I don’t enter my text for a datapoint when submitting with beedroid, the autogenerated entry is along the lines of “via beedroid at 07:41:32 CST”. Which is completely reasonable except that I am not in CST, I’m in CDT, because daylight time is active in my locale. I don’t know if “phone is observing daylight time” is necessarily exposed to beedroid, but I’d rather see no time zone at all (and just thus infer that it was “local time”, whatever that meant when I submitted) than an incorrect one.
This isn’t just an academic/trivial difference: Saskatchewan, e.g., is actually in CST right now: they’re currently GMT-6, whereas I, in the US, am currently GMT-5. I imagine the set of impacted users—those who regularly travel between CST/CDT areas in the same week, or correspondingly between MST/MDT (e.g. people who live near the Arizona border?) is rather small, but I also imagine it’s not quite zero? Whether this matters to them is another question, but still: a bug.

per https://forum.beeminder.com/t/tiny-bug-beedroid-timezone-inaccuracy/9746

**Comment by adamwolf** [comment]
I found the bug and have it fixed locally.  I expect this to get in the next release.

**Comment by dreeves** [comment]
I had this one as a note in the UVI file for "timezone shortnames now DST-sensitive" which it looks like we never tweeted and could (but may be beyond the statute of limitations).

**Comment by adamwolf** [comment]
I'm fine still including it, but also fine not. Should we close this?
