### ISSUE TITLE
Android hoops to jump through: data safety form

### ISSUE THREAD

**Issue by dreeves** [beeminder/beedroid-issues#209]
(via Adam)

https://android-developers.googleblog.com/2021/10/launching-data-safety-in-play-console.html

**Comment by adamwolf** [comment]
I submitted this before the July deadline.  Did you get an email or something?

**Comment by dreeves** [comment]
Oh, no, I just starred it in Slack and Beeminder finally made me do something about it so I gissued it! Closing now. (Thanks!)
