### ISSUE TITLE
Refactor Google Cloud Messaging

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#36]
While debugging some push notification things, I notice that our Google Cloud Messaging receiver  (GcmBroadcastReceiver) uses a Broadcast Receiver, rather than the "current" way of doing things.

See https://developers.google.com/cloud-messaging/android/client

**Comment by dreeves** [comment]
@adamwolf: Anything user-visible about this at all? (I'm working on collecting UVIs...)

**Comment by adamwolf** [comment]
I will be collecting a changelog of everything since the last public
release for a forum thread too, we can double check from that.

I think the best we could get is a user visible non-regression, unless
stopping the recent sporadic "graphs don't stop refreshing" on Android
counts, which, maybe it should?
