### ISSUE TITLE
pause/resume not launching correct goal to pause/resume timer

### ISSUE THREAD

**Issue by bsoule** [beeminder/beedroid-issues#37]
From a user:
not sure what’s going on, but with the newest version of the android app, clicking the notification for a timer is bringing me to the page for a dfiferent goal

the pause/resume button is working though

for example I’ve got a timer going for my `standing` goal , but when I click on it, it opens `read`. Which has a timer that’s not started.

**Comment by adamwolf** [comment]
definitely can reproduce.  *sigh*

**Comment by adamwolf** [comment]
I see the issue.  I'd like to get this released relatively soon, maybe even before the auth stuff.

**Comment by adamwolf** [comment]
This is released.  Closing!
