### ISSUE TITLE
user with active goals not showing up in widget

### ISSUE THREAD

**Issue by bsoule** [beeminder/beedroid-issues#39]
User reports: "The Android list widget stopped working for me perhaps a few weeks ago. It just says "No goals!" but I do have several goals. I tried removing it and re-adding it, but this didn't help." 

I also had them try logging out of the app and back in (under the assumption that this clears the locally cached data. (And I confirmed that they do have active goals :-)

![nogoals](https://user-images.githubusercontent.com/46881/38354131-5197201c-386d-11e8-9808-0efe3745257f.png)

**Comment by adamwolf** [comment]
I saw this two weeks ago.  I looked into it a bit but didn't see what was going on.

**Comment by adamwolf** [comment]
I reviewed every instance of the widget datasource stuff today, and I feel comfortable closing this after some of the changes in the release in progress.
