### ISSUE TITLE
possible error after creating a new account on android + error messaging

### ISSUE THREAD

**Issue by bsoule** [beeminder/beedroid-issues#45]
Had a user get really confused trying to create an account in beedroid. the first time they submitted we successfully created the account, according to our server logs, but then they immediately submitted 2 more times with the same email address and two different usernames, so the next two attempts failed because the email address was already taken. They ultimately went to the website and after three more attempts successfully created a second account...

1) could be a bug on the android app side of things that they weren't logged in to the new account that was created the first time around?
2) what's the error messaging look like when account creation does fail? they didn't seem to be getting the message that the email address was in use, as they were changing up the username but not the email address with their retries (though could be user-error)

**Comment by dreeves** [comment]
Moot now that Beedroid sends you to the website to sign up!
