### ISSUE TITLE
send timezone with user create

### ISSUE THREAD

**Issue by bsoule** [beeminder/beedroid-issues#46]
Beeminder tries to guess timezone when you sign up through the website, but defaults to US Eastern if no timezone is given. Beeminder can be super confusing if your timezone is way off. Can beedroid get the user's timezone and send it along for user creation? This does require an update on the server side of things to actually store a timezone if passed in.

**Comment by adamwolf** [comment]
We don't create users anymore, just aim folks at the website, so this is no longer a thing.
