### ISSUE TITLE
EXIF image issue on graph load

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#48]
There may have been a slight increase in user-reported sync issues, including bad ones where "it only works for a few days after reinstall, and logging in and out doesn't fix it."  One of the users (reported 2018/7/30 to the beedroid support email) has a series of ... bad graph images?

Here's the traceback:

07-30 01:06:10.199  7129  7129 I ExifInterface_JNI: Raw image not detected
07-30 01:06:10.206  7129  7129 W ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
07-30 01:06:10.206  7129  7129 W ExifInterface: java.io.IOException: Invalid marker: 89
07-30 01:06:10.206  7129  7129 W ExifInterface: at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1835)
07-30 01:06:10.206  7129  7129 W ExifInterface: at android.media.ExifInterface.loadAttributes(ExifInterface.java:1475)
07-30 01:06:10.206  7129  7129 W ExifInterface: at android.media.ExifInterface.<init>(ExifInterface.java:1112)
07-30 01:06:10.206  7129  7129 W ExifInterface: at com.beeminder.beeminder.imagezoom.ExifUtils.getExifOrientation(ExifUtils.java:34)
07-30 01:06:10.206  7129  7129 W ExifInterface: at com.beeminder.beeminder.imagezoom.ExifUtils.getExifOrientation(ExifUtils.java:149)
07-30 01:06:10.206  7129  7129 W ExifInterface: at com.beeminder.beeminder.imagezoom.DecodeUtils.decode(DecodeUtils.java:34)
07-30 01:06:10.206  7129  7129 W ExifInterface: at com.beeminder.beeminder.ui.GoalDetailFragment.updateGraph(GoalDetailFragment.java:337)
07-30 01:06:10.206  7129  7129 W ExifInterface: at com.beeminder.beeminder.ui.GoalDetailFragment.reload(GoalDetailFragment.java:301)
07-30 01:06:10.206  7129  7129 W ExifInterface: at com.beeminder.beeminder.ui.GoalDetailView.updateGoal(GoalDetailView.java:597)
07-30 01:06:10.206  7129  7129 W ExifInterface: at com.beeminder.beeminder.ui.GoalDetailView.onCreate(GoalDetailView.java:739)
07-30 01:06:10.206  7129  7129 W ExifInterface: at android.app.Activity.performCreate(Activity.java:6973)
07-30 01:06:10.206  7129  7129 W ExifInterface: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
07-30 01:06:10.206  7129  7129 W ExifInterface: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
07-30 01:06:10.206  7129  7129 W ExifInterface: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
07-30 01:06:10.206  7129  7129 W ExifInterface: at android.app.ActivityThread.-wrap14(ActivityThread.java)
07-30 01:06:10.206  7129  7129 W ExifInterface: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
07-30 01:06:10.206  7129  7129 W ExifInterface: at android.os.Handler.dispatchMessage(Handler.java:102)
07-30 01:06:10.206  7129  7129 W ExifInterface: at android.os.Looper.loop(Looper.java:154)
07-30 01:06:10.206  7129  7129 W ExifInterface: at android.app.ActivityThread.main(ActivityThread.java:6823)
07-30 01:06:10.206  7129  7129 W ExifInterface: at java.lang.reflect.Method.invoke(Native Method)
07-30 01:06:10.206  7129  7129 W ExifInterface: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1557)
07-30 01:06:10.206  7129  7129 W ExifInterface: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by adamwolf** [comment]
Based on a somewhat related issue, I see https://github.com/square/picasso/issues/1504 which mentions:

> I've tried to compile Picasso using the android support library for ExifInterface and it seems to fix the issue
> For instance, I've added "com.android.support:exifinterface:25.3.1"
>
>to the build.gradle and edited every ExifInterface call to use android.support.media.ExifInterface >instead of the native android.media.ExifInterface

I could take a look and see if we can do that.

**Comment by adamwolf** [comment]
I have not seen this in analytics for a very long time.

**Comment by adamwolf** [comment]
This has been showing up in my dev environment.

**Comment by adamwolf** [comment]
This is an issue only in that it make the logs noisy--it is doing the right thing, codewise.  This will go away if we do #127

**Comment by krugerk** [comment]
Could you confirm this no longer appears in recent versions of the app, those since #127?
