### ISSUE TITLE
error when low on space on device

### ISSUE THREAD

**Issue by bsoule** [beeminder/beedroid-issues#49]
there's this thing where the android app stops syncing when your phone gets low on available space and if you free up space it starts to sync again (https://help.beeminder.com/article/62-android-app#sync). 

this is probably due to things mostly beyond our control, and other apps will probably start to have weird issues too if you totally run out of space (though beedroid may be worse than most apps -- sort of a canary in the coal mine). but can the app be self-aware about the issue and give error messages when this happens?

**Comment by adamwolf** [comment]
Yes, we can!  A good way to do this is with File.getUsableSpace().

@dreeves, wanna tagify this?

**Comment by adamwolf** [comment]
We now send the usable space / total space in the Send Feedback debug information.

**Comment by adamwolf** [comment]
We won't need to care about this once the syncworker stuff is done, but it will still be in the feedback view.

I'm OK closing this once the current release-in-progress is out.
