### ISSUE TITLE
Support HH:MM:SS

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#51]
Beedroid does not currently support this.

**Comment by dreeves** [comment]
The ground truth for these regexes lives at http://d.glitch.me (see the monster regexes at the bottom of the page).

The one we want in Beedroid is

```"^\\s*[\\+\\-]?(?:\\d+\\.?\\d*|\\.\\d+)|\\d+st(?:\\d+\\.?\\d*|\\.\\d+)?|(?:\\d*\\:[0-5]\\d(?:\\:[0-5]\\d)?|0?0?\\:\\d\\d)\\s*$"```

**Comment by adamwolf** [comment]
Done in 2.10.8.
