### ISSUE TITLE
Split the Notification types into multiple channels

### ISSUE THREAD

**Issue by quintrino** [beeminder/beedroid-issues#54]
So currently all notifications on the app are in a single channel. 

https://developer.android.com/training/notify-user/channels

But it occurs to me it could be good to divide each goal or at least timer vs eep notification to allow better control over what notifications get high priority and what do. 

An example use case is I don't want to get timer notifications during Do Not Disturb, but I may want it for an Eep 5 minutes til deadline message.

**Comment by adamwolf** [comment]
This is actually already done in the upcoming release that targets Android O. :)

**Comment by quintrino** [comment]
Awesome!

Goal based or timer vs eep based? 

(Really all I want is to disable my phone goal timer so either will achieve my needs, just curious)

Is there an ETA? 

Thanks for always doing such amazing work!

**Comment by adamwolf** [comment]
Once it's beta-able, I can announce in the forum asking for beta users.
There is some fundamental restructuring in this update so we'll need a
bunch of testing.

**Comment by quintrino** [comment]
Just wondering if feature got released and I missed it somewhere? How do I check if I'm in the Beedroid Beta?

**Comment by adamwolf** [comment]
It has not yet been released to beta or otherwise. There were some priority
bumps in the middle there, but Beedroid is back to being the main thing I'm
working on here!

I will check to see if you are on the beta list and let you know.

**Comment by adamwolf** [comment]
@quintrino, if you would like to be added to the beta list, send an email from your Google account to beedroid@beeminder.com.  Thanks!
