### ISSUE TITLE
possible error with timey datapoint validation 

### ISSUE THREAD

**Issue by bsoule** [beeminder/beedroid-issues#55]
00:10 is indicated as invalid (for one user on one device). I can't reproduce, but they are reproducing reliably I guess? But only on one device (on phone, not tablet).

![screenshot_20181014-073403](https://user-images.githubusercontent.com/46881/46963222-ebb56300-d059-11e8-803a-84db8ab7a8c6.png)

**Comment by adamwolf** [comment]
"so that is based on regional settings, somehow
if that person switches their regional language to english, it works
and then they switch back to italian and its broken again"

**Comment by adamwolf** [comment]
This has been seen recently by another user.

**Comment by adamwolf** [comment]
I was unable to reproduce in Italian vs English after the latest HH:MM:SS update.
