### ISSUE TITLE
No notifications on Android 8.1

### ISSUE THREAD

**Issue by saranli** [beeminder/beedroid-issues#59]
I got a new phone with Android 8.1, and have not received any Beeminder notifications since then. There is just the persistent notification, with just the text "Keep your goals in sync!". Screenshot:
![Screenshot_20190318-210422](https://user-images.githubusercontent.com/1292086/54552793-f46fe380-49c1-11e9-9fd5-17b20446be61.png)

Beeminder related notification categories seem to be enabled:
![Screenshot_20190318-210834](https://user-images.githubusercontent.com/1292086/54552886-24b78200-49c2-11e9-9b9d-503c5a11528b.png)

But when I click on the settings icon at the notification, only 1 of 3 categories seem to be enabled:
![Screenshot_20190318-211032](https://user-images.githubusercontent.com/1292086/54552988-5d575b80-49c2-11e9-94ff-a130092e30f6.png)

**Comment by adamwolf** [comment]
Per Slack feedback, saranli has notifications but they are not working consistently.  No feedback yet for 2.10.2.

**Comment by adamwolf** [comment]
I hope this is fixed as of 2.10.5.

**Comment by adamwolf** [comment]
@saranli Is this still happening?  do you think I can close this?
