### ISSUE TITLE
Visual glitches in new version

### ISSUE THREAD

**Issue by dreeves** [beeminder/beedroid-issues#60]
Here's everything I found from 10 minutes of exploring the app on two phones side by side, one with the new version (2.9.2 build 11193) and one with the old (2.7.0 build 10794):

In Review by @dreeves 
- [ ] the cancel/ok buttons for logging out are squished together

(Feel free to move some to a wontfix section down here)
Done
- [x] no horizontal dividing line after the header on most (all?) screens
- [x] section headings in app settings are blue instead of all caps
- [x] possibly fewer datapoints fit on the goal screen but that might be the phones i'm comparing with
- [x] gray background instead of black (worst thing about this may be that the goal blurbs in the dashboard view have a blue gradient that used to fade into the background and now is more of a big ugly rectangle)
- [x] button labels are all caps
- [x] missing beeminder logo at top left of all screens
- [x] the "ROLLBACK" button text wraps with the "CK" on a new line
- [x] no logo on the summary widget
- [x] no refresh button on the summary widget
- [x] worse date picker for datapoint editing (especially in that it makes you scroll to see the update/delete buttons on my phone)

Moved to their own issue
- [x] lost the visual indicator after "swipe to change entry method"
- [x] lost the toast popups telling you you've switched entry method ("Direct datapoint entry", "Tally counter entry", "Timer entry")

**Comment by bsoule** [comment]
button label all-caps might be fine in general, but if going for it i think the font size + padding on the buttons might want adjusted

**Comment by adamwolf** [comment]
The indicator that showed the dots when swiping between input methods doesn't work anymore and isn't maintained.  I need to find a new replacement but it won't happen before the first public release of the updated app.  I will take a look at most of these real soon.

**Comment by adamwolf** [comment]
Also, this may not be obvious--outside of the dots when swiping input methods, none of these changes were things done on purpose. 😿

**Comment by adamwolf** [comment]
@dreeves wanna review the done ones as being done?  Thoughts on how much you love the remaining ones?  If we're good like we are, want to remove the MEN label?  If you really don't care about the remaining ones, maybe zap the whole thing?

**Comment by dreeves** [comment]
I checked off a couple that seemed better or at least definitely no worse in the new version.

The possibly fewer datapoints one might be because you accidentally stuck a test string ("abc") in between the baremin/hardcap line and the datapoints?

The squished cancel/ok buttons is extremely minor but unambiguously better in the old version where they're as big and spread out as possible instead of just the words being links.

**Comment by adamwolf** [comment]
Whoops on the ABC.  That's a new one, I was testing putting in the next
Zeno time or reason right there, but I didn't like it.  I didn't intend to
release that to testing.  Whoops.

**Comment by adamwolf** [comment]
Fixed ABC in latest commits.

**Comment by adamwolf** [comment]
It is not clear to me where the screen size is going now.  I thought there was a gap between the image and the top bar, but that is due to aspect ratio of the raw image--double tap it to zoom and you'll see what I mean.

I can dig into the imagezoom code to resize that initial image area.  Do you want me to tweak font sizes or jam things closer, or what do you want me to do here?

**Comment by adamwolf** [comment]
The gap is deceptive.  The image spacing is what's left over of partial rows.  That chunk of code was a brain burner.  I left it with some more comments.

I added an extra row by squeezing the dots indicator a few pixels.  It's pushed, will be released in the next beta.

**Comment by dreeves** [comment]
sorry i was slow on this! i wasn't actually certain this was even a regression, as opposed to differences in screen sizes. it would be nice to have identical devices side by side with old vs new. but i think this was the last possible regression and you just nailed it so, yay!

**Comment by adamwolf** [comment]
Logout dialog should be fixed today.

**Comment by adamwolf** [comment]
All of these are done!  Do I remove the MEN label when it's zapped, for easier searching, or do you want that archived?

**Comment by dreeves** [comment]
> Do I remove the MEN label when it's zapped, for easier searching, or do you want that archived?

No, just close and add `zap` label [1]. By default clicking the `MEN` label shows you open issues only, so there's no advantage (that I can think of...?) to removing the `MEN` label.

[1] Further nitpicky protocol thing that let's say tentatively we needn't actually be nitpicky about but maybe it's an ideal to shoot for or maybe someday we'll find the discipline valuable:

Closing an issue has two stages:

1. Applying the lowercase label saying [why/how it's resolved](http://blog.beeminder.com/buglabels "In short: the all-lowercase labels say why/how the issue was resolved and the uppercase labels are, like, ontological")
2. Actually closing it

Those can happen in either order but two different people should do them, and one of those people should be the one who opened the issue.
