### ISSUE TITLE
Ruthlessly purge settings: "Check for graph updates"

### ISSUE THREAD

**Issue by dreeves** [beeminder/beedroid-issues#61]
I don't think this should be a user-visible setting. I know there's technically a tradeoff to made and that people's circumstances, like how much they pay for data, mean that different tradeoffs may make sense for different people. But the fraction of people equipped to make that tradeoff rationally is tiny. Everyone else will fruitlessly agonize at best or set it to something stupid at worst. (Ok, actual best case is they ignore it completely and it just contributes slightly to the Settings page feeling overwhelming and cluttered.) 

Even I have no idea what's sensible. Mine is currently set to 15 minutes. Did I choose that at some point or is it the default? Is that dumb and wasteful to poll so often? Considering this setting does nothing but vaguely stress me out.

Also maybe we want flexibility for the algorithm to be smarter or adaptive in some way. We shouldn't commit to a particular polling frequency.

**Comment by dreeves** [comment]
(that's my argument! i convinced myself in the course of typing it but don't be shy about disagreeing!)

**Comment by adamwolf** [comment]
When we remove the current sync stuff and replace it with a WorkManager (#77), we'll be reworking all of the syncing stuff.  I think it makes sense to remove this then.  @dreeves if you agree, wanna pull the MEN label?

**Comment by dreeves** [comment]
Done. Not sure if this means we close it as snoozed (`zzz`) for now. I guess it depends how much we mind open issues hanging around that aren't ready to be acted on. (Tentatively adding the label but not actually closing.)
