### ISSUE TITLE
Ruthlessly purge settings: "Enable vibration" in general settings

### ISSUE THREAD

**Issue by dreeves** [beeminder/beedroid-issues#65]
[says] Adam: that is now an OS setting per notification channel

**Comment by adamwolf** [comment]
Thinking about it, I may need to look at our dashboard to see how many people are on older android versions.

**Comment by adamwolf** [comment]
So older Android versions do not allow you to set this in Android Settings.

Proposal: we release something close to the current beta, and then in X weeks after release, we look at our userbase and see if we can easily remove this or if we should keep it until those folks upgrade.

**Comment by adamwolf** [comment]
This has been released in Beedroid 5.
