### ISSUE TITLE
Kinda silent failure adding widget when not logged in

### ISSUE THREAD

**Issue by dreeves** [beeminder/beedroid-issues#66]
If you try to add a widget when not logged in it acts like it's working and then the widget just disappears. That may pretty unavoidable or we may want to close this as simply not worth it, but logging the gissue just in case there's a easy error message we could throw in.

**Comment by adamwolf** [comment]
User reports that this is fine with goal widget, but fails with summary widget.

**Comment by adamwolf** [comment]
As of the next release, you'll get a little popup that says you can't add a widget before logging into Beeminder.

**Comment by adamwolf** [comment]
This has been released in Beedroid 5.
