### ISSUE TITLE
Goalname that's a prefix of another goalname breaks search

### ISSUE THREAD

**Issue by dreeves** [beeminder/beedroid-issues#72]
UPDATE: Now fully reproducible!

## Reseminata

1. Create a goal with goalname "foo"
2. Create a goal with goalname "foobar"
3. Click the magnifying glass in Beedroid
4. Type "foo" (or any subset of "foo" that makes foo appear in the list)
5. Tap it

## Expectata 

Go to foo's goal page.

## Resultata

Blank "Search results" page. Subtitle: "Query: username/foo"

## Nota Nebulosa

It all works fine for pairs of goals that merely _share_ a prefix, like "beebrain" and "beemail". And you can still get to the foo goal by scrolling to it and tapping it, ie, without using search.

**Comment by adamwolf** [comment]
I see this too, but it is tricky to reproduce.

**Comment by dreeves** [comment]
Oh, is it that "ent" is a prefix of "entomophobia"? [UPDATE: yup]

"Shrug, maybe, but this is too low priority to even find out for sure" would be a fine answer. As would be "oh, right, lightbulb, one-line fix!"

**Comment by dreeves** [comment]
I got bit by this again with "d/sugar" and "d/sugarbowl" and have now fixed the gissue so it's a proper defectus demonstrandum.

**Comment by adamwolf** [comment]
It's slightly bigger than this.  I've had issues even when multiple goals share a common prefix.

**Comment by adamwolf** [comment]
Got this fixed up.  It should be in the next release.
