### ISSUE TITLE
Date formatting in data entry questions

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#73]
We're seeing some user confusion, even with people who know Beeminder quite well, around the date entry in the goal setting view.

For instance, at the end of April, it says "30", and then the next day, it shows "5 1" and the space isn't very big.

Are we in love with reminding users of the format for the email bot et al here?  If so, is there a better usability separator than that little space?  Should there be two boxes there, one usually blank?  Should we fill the first box always with the month number?

@dreeves

**Comment by shanaqui** [comment]
A bigger space would do it too! Also, when the numbers are double digits, it becomes quite obvious that it's "number space number" rather than "two digit number", so 05 1 would probably do it.

**Comment by dreeves** [comment]
This is a mild can of worms, though a project I very much want to tackle. I think one prereq is to refactor the rails code to use the monster regex from http://d.glitch.me everywhere. That paves the way to improving the data format (possibly pretty easily at that point -- I'm not sure this is a huge project!).

In the meantime, I think I advocate just making that space bigger.

**Comment by adamwolf** [comment]
Will add larger space.

Adam.commits.to/add_larger_date_separator

**Comment by adamwolf** [comment]
I added some space.

![before](https://user-images.githubusercontent.com/35681/57232193-b6666780-6fe1-11e9-951b-7a1785d0ceb1.png)

![after](https://user-images.githubusercontent.com/35681/57232196-b8302b00-6fe1-11e9-8232-09427469c301.png)

**Comment by adamwolf** [comment]
This has been released to internal testers as 2.10.2.
