### ISSUE TITLE
can we do a sync before initiating a notification?

### ISSUE THREAD

**Issue by bsoule** [beeminder/beedroid-issues#75]
from a user: "could you make the android app initiate a sync before playing the notification sound? As it stands, if I enter data to  tell the web site that I won't derail in a few hours, the phone will still blare right until the end. It just feels stressful and punishing. I am running a de-Googled phone (with LineageOS and MicroG), so maybe the lack of push messaging is contributing to this bug."

**Comment by bsoule** [comment]
alternate title: "do we have fallbacks / robustness for goal alerts and syncing on devices that don't have or don't allow push notifications?"

**Comment by adamwolf** [comment]
I think this is a good idea.

I also did not realize that folks can run without push notifications.

**Comment by adamwolf** [comment]
I would like to slot this in as part of the WorkManager transition.

**Comment by adamwolf** [comment]
We should do this with #77, and have a "recently updated threshold"

**Comment by adamwolf** [comment]
We're going to be getting notifications from the server directly as of the next release.  Closing.
