### ISSUE TITLE
Pick Foreground Service Notification styling

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#82]
@dreeves I now know how to make a tap on the foreground service notification take users directly to the screen where they swipe to turn it off.  Do we want to make the notification say something like "Hey, having this notification helps syncs and notifications work right now, but you can hide it by tapping and then selecting "Hide Foreground Services notifications""?

**Comment by dreeves** [comment]
That sounds ok to me. Let me also capture some feedback and notes about this:

> works great, there is just a persisting icon in the notification tray that reads 'keeping your goals in sync'. I restarted the phone but the icon will not disappear.
> great work!

maybe we should own it harder and have the text be "persistent notification!" since "keeping your goals in sync" sounds like corporate weaselmouthery for user-hostile shenanigans.

as you pointed out, Tasker says "Mandatory persistent notification, tap to hide"

more adam notes:

We can implement tapping on it taking you directly to settings

We can also make tapping on it take you to the support website where we explain what it is why it is and how to disable it

If you expand it, there is a learn more option that takes you to that website today.

It is not much work at all to switch between these, so feel free to pick the next one to try... Or don't, and we will leave it :p

Also, in the past six months, enough other things have changed that if we change how we do syncing, and we push notifications from the server and are OK with sometimes more inaccurate offline notifications, we could get rid of it for good!

**Comment by adamwolf** [comment]
Other ideas:. We could add two actions to the notification.  It has one
right now, which says "Learn More" which users don't see since it is so
bland.  What about linking to the support page with an action of "What is
this?" Or "why is this here?", and then linking to the settings page with
an action titled "hide this notification"?

**Comment by dreeves** [comment]
My gut feeling: Make it as short and unobtrusive as possible. Like just "Permanotification!" with no click-to-expand.

**Comment by adamwolf** [comment]
I'm setting that now.  I'd kinda like to make the Notification Channel name match, so if they get into Settings that they aren't confused by "Foreground Services."

**Comment by adamwolf** [comment]
Lemme know what you think when 2.10.9 comes across.  I need to log into the help page and adjust the text just a bit, and then if it looks good to you we can zap this!

**Comment by adamwolf** [comment]
This is done as of 2.10.9, released in beta.

**Comment by dreeves** [comment]
Better and better! I think we talked about this before but I have an example (Jiobit) that seems to be doing this better in terms of space efficiency. Though maybe they have a different kind of notification. There's only appears when I'm connected to the Jiobit device via bluetooth. 

Also for some reason our permanotification is really hard to click/tap on. Like I have to click in the whitespace below it, not on it?

![image](https://user-images.githubusercontent.com/9928/58217213-9956b780-7cb6-11e9-9783-d58f80cd5f80.png)

**Comment by adamwolf** [comment]
So I'm not sure how they're doing it, *unless* they're not doing it to create a foreground service.  That looks just like an IMPORTANCE_MIN notification.  One way to tell is does that icon show up in your notification bar?  For IMPORTANCE_MIN, it won't.

https://developer.android.com/reference/android/app/NotificationManager.html#IMPORTANCE_MIN

What I did here is make an IMPORTANCE_LOW notification, and then gave it subtext without giving it a title.  I think that Android gets a little confused there, and puts the subtext in the tiny text up in the top line.  I think the confusion is also why it's hard to click.

If I set it as a title, it's like a regular notification with a line of slightly bigger text. and is easy to click.

**Comment by dreeves** [comment]
Ah, you're right, Jiobit's icon does not appear on top. Mystery solved!

I shall leave the clickability/space tradeoffs to you. It might feel slightly broken this way with the blank space, but I don't know. Android has made it all a pretty no-win situation!

**Comment by adamwolf** [comment]
Hmm.  Let's see what users have to say in the forum?  "Bigger/more obvious how to hide?" or "smaller/harder to find it out?"

**Comment by dreeves** [comment]
The more I think about it the more I think the blank long text, the way that creates spurious whitespace, and especially the concomitant clickability issue, is just wrong. Let's come up with some good copy for the short and long text. We might need @bsoule to make this cuter / more beemindery but off the top of my head:

SHORT: Permanotification!
LONG: Learn about the sadness necessitating this

(Do I have that right that the way to avoid the whitespace/clickability issue to have both short and long text? Let's definitely still minimize the space this takes up -- don't let it wrap, etc -- subject to non-brokenness constraints.)

**Comment by adamwolf** [comment]
I think it's shortest if we just have one line of text.  The way to avoid the whitespace/clickabilty issue is to have title text--like what's in zenos.  We don't actually have to make it expandable, either, so we could just with Permanotification!, and once a user clicks it once, we point them at a small explanation of what it is, why it is, and most importantly how to hide it forever

**Comment by adamwolf** [comment]
zapped in 3.0.0
