### ISSUE TITLE
Verify summary widget reload behavior

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#88]
We have a user report that "The list widget no longer updates on pressing the “reload” button repeatedly"

**Comment by dreeves** [comment]
I'm also seeing this! The refresh button (upper right) on the summary widget (the one with the list of most urgent goals) seems to not be clickable at all anymore. On the public Beedroid it briefly changes from the refresh icon to a clock icon suggesting that it's doing the refresh.

**Comment by adamwolf** [comment]
zapped in 3.0.0
