### ISSUE TITLE
custom notification sound

### ISSUE THREAD

**Issue by bsoule** [beeminder/beedroid-issues#92]
user reports on 5/28: 

> The notification sound became the system default sound, even though I had something else configured before the upgrade, and even though the app still shows my custom sound, and even though I re-configured the custom sound. I haven't tried deleting all app data in  the android settings yet.

**Comment by adamwolf** [comment]
User confirmed that they were able to set the custom sound via the Android settings, just the in-app settings.

I am wondering if we should only show the custom-sound-setting stuff for folks who have Android versions old enough that Android doesn't provide this feature.  Do we know what other apps do? (I guess I don't do this in anything I use!)

**Comment by adamwolf** [comment]
Confirmed by multiple users.

**Comment by adamwolf** [comment]
Custom notification sounds won't work after the Android permission change without a lot of effort.   25% of our users are on Android 8 or higher, where they can set custom sounds in the Android Settings under Apps & Notifications > Beeminder.

Custom sounds were causing a crash.  I have removed custom sounds as of 3.1.0.

**Comment by adamwolf** [comment]
This has been removed and can be closed.
