### ISSUE TITLE
BootReceiver Crash

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#96]
Sometimes, the start-at-boot code is crashing.  It appears to be complaining that the Beeminder class is not in the manifest which doesn't really make sense.  It's affecting a good number of users, but I haven't yet reproduced it.

**Comment by adamwolf** [comment]
Fixed by https://github.com/beeminder/beedroid-hist/pull/69.

**Comment by dreeves** [comment]
(awaiting confirmation that it's fixed in the wild before closing)

**Comment by adamwolf** [comment]
Fixed in wild.  No longer seen in analytics.
