### ISSUE TITLE
Bad formatting in in-app changelog

### ISSUE THREAD

**Issue by dreeves** [beeminder/beedroid-issues#97]
Note missing newlines:

![image](https://user-images.githubusercontent.com/9928/60153966-bccfbf00-979a-11e9-82f7-e06399590214.png)

Maybe it needs to be space-space-newline per official markdown syntax?

**Comment by adamwolf** [comment]
Sorry, it was autoclosed.

**Comment by dreeves** [comment]
oops, not fixed for me in 3.0.2 -- still a bunch of missing newlines, maybe different ones.

**Comment by adamwolf** [comment]
Got it this time :)
